Sowri
Sowri19/careWallet pull request #8
Opened 2024-01-04 06:41 UTC by Sowri19

2024-01-04 07:03 UTC, shashibyadav requested changes

2024-01-04 07:03 UTC, shashibyadav commented on src/Components/Camera/index.tsx
> +    <OverlayContainer>
change it to common styled view as <Container> in shared styles

2024-01-04 07:03 UTC, shashibyadav commented on src/Components/Camera/styles.tsx
> +export const ButtonText = styled.Text`
use common button text style in shared styles

2024-01-04 07:03 UTC, shashibyadav commented on src/Components/Camera/styles.tsx
> +export const ButtonText1 = styled.Text`
use common style

2024-01-04 07:03 UTC, shashibyadav commented on src/Components/Camera/styles.tsx
> +export const Text = styled.Text`
make a color const in app wide colors file and use it here

2024-01-04 07:03 UTC, shashibyadav commented on src/Pages/Login-Register/Register/AccountCreation/Step1/SignUp.tsx
> +    navigation.navigate('IDVerification');
revert it back to step2 of sign up

2024-01-04 07:03 UTC, shashibyadav commented on src/Pages/Login-Register/Register/AccountCreation/Step5/index.tsx
> +    <Container>
use common container style

2024-01-04 07:03 UTC, shashibyadav commented on src/Pages/Login-Register/Register/AccountCreation/Step5/styles.tsx
> +export const Container = styled.View`
remove this, this is a duplicate style

2024-01-04 07:03 UTC, shashibyadav commented on src/Pages/Login-Register/Register/AccountCreation/Step6/index.tsx
> +    <Container>
use common style

2024-01-04 07:03 UTC, shashibyadav commented on src/Pages/Login-Register/Register/AccountCreation/Step6/styles.tsx
> +export const Container = styled.View`
duplicate style

2024-01-04 07:03 UTC, shashibyadav commented on src/utilities/FacialRecognitionOverlay.png
move this image to shared media folder

2024-01-04 07:03 UTC, shashibyadav commented on src/Components/Camera/styles.tsx
> +export const Container = styled.View`
remove duplicate style

2024-01-04 07:03 UTC, shashibyadav commented on src/Components/Camera/index.tsx
> +  useEffect(() => {
try not hit permission api in this useEffect, try to make it global in app.tsx file and store granted permission status in redux state for ease access in all pages instead of local state of this page.

2024-01-04 17:17 UTC, Sowri19 commented on src/Components/Camera/index.tsx
> +    <OverlayContainer>
fixed

2024-01-04 17:17 UTC, Sowri19 commented on src/Components/Camera/styles.tsx
> +export const ButtonText = styled.Text`
fixed

2024-01-04 17:17 UTC, Sowri19 commented on src/Components/Camera/styles.tsx
> +export const ButtonText1 = styled.Text`
fixed

2024-01-04 18:02 UTC, Sowri19 commented on src/Components/Camera/styles.tsx
> +export const Text = styled.Text`
fixed

2024-01-04 18:03 UTC, Sowri19 commented on src/Pages/Login-Register/Register/AccountCreation/Step6/index.tsx
> +    <Container>
fixed

2024-01-04 18:03 UTC, Sowri19 commented on src/Pages/Login-Register/Register/AccountCreation/Step6/styles.tsx
> +export const Container = styled.View`
fixed

2024-01-04 18:03 UTC, Sowri19 commented on src/utilities/FacialRecognitionOverlay.png
fixed

2024-01-04 18:03 UTC, Sowri19 commented on src/Components/Camera/styles.tsx
> +export const Container = styled.View`
fixed

2024-01-05 05:56 UTC, Sowri19 commented on src/Components/Camera/index.tsx
> +  useEffect(() => {
fixed

2024-01-05 05:56 UTC, Sowri19 commented on src/Components/Camera/index.tsx
> +    <OverlayContainer>
fixed

2024-01-05 05:57 UTC, merged